### PR TITLE
Improvements to the rest of the outside textures with in-game comparisons

### PR DESCRIPTION
**Pull request by CreamDream1943**
Decided to update the rest of the textures that had slightly inaccurate colors, those being the clock, dark brick, moat wall, waterfall, and sand textures (also boosted the contrast of the window's boarder, realized the decals weren't dark enough). I used the same technique with the window texture of darkening/desaturating the textures to see how they compared with footage. A few of the improvements made:

- The beta sand was around 30 percent less saturated than the final's, so fixed that (the different shading on the pathway makes this harder to tell in most places, so I suggest looking at the fully illuminated spots).

- The BG of the clock textures was a very light gray color, which is most clear in the third and fourth comparison gifs.

- The middle section of the moat walls were less saturated.

My primary reference material was this footage https://www.youtube.com/watch?v=3aCDsogq8fQ&t=19s. What's cool with this clip is that the colors are all affected equally for the most part, so if you wanna compare your texture with footage you can simply darken/desaturate it (going off of how the color of other objects are affected, like Mario) to see how it matches. Comparisons below:

1 (darkened)

2 (darkened)

bandicam 2022-12-07 04-39-25-861
This screenshot shows the sand's color better. In all the footage, the sand is closer to Mario's skin tone.

Dsnitro_sm64ds

More on the sand texture, this might sound a little far-fetched, but the sand texture used in the proto SM64DS screenshot could also possibly be the one used in the patent/Spaceworld maps. I desaturated TPP's sand texture to match with the screenshot out of curiosity, which ended up matching exactly with the values of Spaceworld's sand, sooo... there's that too I guess.

### CODE REVIEW

**Comment by CreamDream1943** [comment]
ugly youtube playback bar

**Comment by CreamDream1943** [comment]
I've also noticed many geometry, uv, and shading inaccuracies. If the assets were released I could try fixin em and do other stuff for the project

**Comment by GodlyGH** [comment]
image
i noticed here it's flat, is it because of culling or is it just a single tri and nothing else since the devs were probably still working on the castle

**Comment by CreamDream1943** [comment]
> image i noticed here it's flat, is it because of culling or is it just a single tri and nothing else since the devs were probably still working on the castle

The model is just slightly off. Lots of little things like that could be tweaked.

**Comment by GodlyGH** [comment]
https://cdn.discordapp.com/attachments/845405298974130226/1050387777046466640/IMG_2739.jpg ah turns out in spaceworld 95 there was just shitty culling. here's a patent image

**Comment by CreamDream1943** [comment]
I'm aware, yeah admittedly it's strange cause the final version is like that too. But you're saying culling is responsible for this? The entire castle wouldn't even be visible from the start if the culling were that high, unless I misunderstood what you meant by culling. The likelier explanation is that they removed those tris in Spaceworld, but brought them back later. Further, the back spires that were added after the show seem to use this design as well. bandicam 2022-12-08 10-55-42-233
64f09023-6192-47c5-8b81-f92c8fc68947
00d0883d-4a40-4dcd-9b4e-87b605b31f97

Also about the patent spires, with the ds model it's revealed that they cheated in joining the verts of those triangles with the rest of the geometry. Deleting them and connecting the remaining verts produces a close match to shoshinkai, so it's safe to say this was done. By the way, the patent roof's geometry is different from the shoshinkai, final, and ds maps.

**Comment by GodlyGH** [comment]
https://cdn.discordapp.com/attachments/755764408461951076/1050517106992615486/IMG_4014.png here confirms it's not flat in spaceworld 95, seems my eyes werent workin right

**Comment by CreamDream1943** [comment]
Ah never mind lol

**Pull request closed without merging**
