### PR TITLE
Make level lighting more harsh and consistent.

### PR DESCRIPTION
**Pull request by iProgramMC**
I think the SpaceWorld demo used a uniform type of lighting, before they messed with it on Mario and other models in 1996. Most of the models use a consistent type of lighting, with scale 4 (the ambient color is 4 times less than the diffuse color).

I've seen inaccuracies in some levels because of this, notably WF and CCM, but others too, where the level lighting just wasn't harsh enough.

Here are a few examples:

1. Snow Slider
Reference screenshot:
image

Early:
image

Now: (after this PR)
image

2. Mountain
Reference screenshot:
image

Inaccurate:
image

Accurate:
image

### CODE REVIEW

**Comment by iProgramMC** [comment]
This closes #60 too.

**Comment by iProgramMC** [comment]
Do you use tabs or X amount of spaces?

**Comment by Fluvian** [comment]
4 spaces.

**Comment by iProgramMC** [comment]
I'll update it, theb

**Comment by Fluvian** [comment]
Looks good.

**Pull request merged**
